/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lexer;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Lexer lexer = new TokenLexer();
        InputStream stream = new TextStream("let name;let=troo\n    'asdf6236&\"\"4$#..\"436';");
        TokenOutput output = lexer.lex(stream);

        System.out.println("why did it fail?");
    }
}
